# NDArray常用API

In [67]:
import mxnet as mx
from mxnet import nd
import numpy as np
import time

## 1.full
生成一个指定shape并按照指定值填充的矩阵

In [8]:
a = nd.full(shape = (2, 3), val = 1)
print(a)


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>


## 2.reshape
将矩阵reshape为指定的形状，shape是一个tuple。如果tuple中的数字是
+ 0:该维度保持不变
+ -1：该维度是剩余所有维度的乘积
+ -2：复制剩余维度
+ -3：使用两个连续维度的乘积
+ -4：把一个维度分成两个维度，这两个维度是由-4之后的两个数字决定的。

In [13]:
a = nd.full(shape = (2, 3, 4), val = 2)
print(1, a.shape)
print(2, a.reshape(0, 4, -1).shape)
print(3, a.reshape(0, -2).shape)
print(4, a.reshape(0, -3).shape)
print(5, a.reshape(-4, 2, 1, 0, 0).shape)

1 (2, 3, 4)
2 (2, 4, 3)
3 (2, 3, 4)
4 (2, 12)
5 (2, 1, 3, 4)


## 3.reshape_like
将矩阵reshape为和指定矩阵相同的形状

In [14]:
a = nd.full(shape = (2, 3, 4), val = 3)
b = nd.zeros(shape = (2, 12))
print(a.reshape_like(b).shape)

(2, 12)


## 4.expand_dims
在某个位置增加一个维度

In [16]:
a = nd.array([4, 2])
print(a.shape)
print(a.expand_dims(axis = 1).shape)

(2,)
(2, 1)


## 5.squeeze
去掉某个为1的维度

In [18]:
a = nd.array([[1, 2]])
print(a.shape)
print(a.squeeze(axis = 0).shape)

(1, 2)
(2,)


## 6.split
把一个矩阵分成多个矩阵的list,需要指定```num_outputs```和```axis```两个参数

In [24]:
a = nd.full(shape = (3, 4, 5), val = 6)
b = nd.split(data = a, num_outputs = 3, axis = 0)
print(b)

[
[[[6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]]]
<NDArray 1x4x5 @cpu(0)>, 
[[[6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]]]
<NDArray 1x4x5 @cpu(0)>, 
[[[6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]
  [6. 6. 6. 6. 6.]]]
<NDArray 1x4x5 @cpu(0)>]


## 7.save & load
保存和加载矩阵

In [25]:
a = nd.full(shape = (2, 3), val = 7)
nd.save("7", a)
b = nd.load("7")
print(a)
print(b)


[[7. 7. 7.]
 [7. 7. 7.]]
<NDArray 2x3 @cpu(0)>
[
[[7. 7. 7.]
 [7. 7. 7.]]
<NDArray 2x3 @cpu(0)>]


## 8.diag
  获取矩阵对角线上的数据或者根据一个1D的矩阵构建一个对角矩阵，指定其对角线元素。
  
  通过参数```k```可以指定对角线的偏移量，为正向右偏移，为负向左偏移。
  
  通过```axis1```和```axis2```两个参数来指定子矩阵，操作时去掉这两个维度，得到剩余的shape，从这个两个维度得到diag,然后加到剩余的shape之后。比如shape为(2, 3, 4, 5)的矩阵axis1 = 0，axis2 = 2，k = 0,输出的shape是 (3, 5, 2).

In [34]:
a = nd.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(nd.diag(a))
print(nd.diag(a, k = 1))
print(nd.diag(a, k = -1))
b = nd.array([1, 2])
print(nd.diag(b))

x = nd.array([[[1, 2],
      [3, 4]],

     [[5, 6],
      [7, 8]]])

print(nd.diag(x, axis1=-2, axis2=-1))


[[1. 2. 3.]
 [4. 5. 6.]]
<NDArray 2x3 @cpu(0)>

[1. 5.]
<NDArray 2 @cpu(0)>

[2. 6.]
<NDArray 2 @cpu(0)>

[4.]
<NDArray 1 @cpu(0)>

[[1. 0.]
 [0. 2.]]
<NDArray 2x2 @cpu(0)>

[[1. 4.]
 [5. 8.]]
<NDArray 2x2 @cpu(0)>


## 9.tile
不断重复平铺一个矩阵

In [35]:
a = nd.array([[1, 2], [3, 4]])
print(nd.tile(a, reps = (2, 2)))


[[1. 2. 1. 2.]
 [3. 4. 3. 4.]
 [1. 2. 1. 2.]
 [3. 4. 3. 4.]]
<NDArray 4x4 @cpu(0)>


## 10.pad
对矩阵的边缘进行填充。只支持4D或者5D的矩阵。参数```pad_width```指定了各个轴前、后两个方向需要填充的宽度，前两个轴必须为0。

In [40]:
x = nd.array([[[[  1.,   2. ,  3.],
       [  4. ,  5.  , 6.]],

      [[  7.  , 8.  , 9.],
       [ 10.,  11.,  12.]]],


     [[[ 11. , 12.,  13.],
       [ 14.,  15.,  16.]],

      [[ 17.,  18.,  19.],
       [ 20.,  21.,  22.]]]])
print(nd.pad(x, mode="constant", constant_value=0, pad_width=(0,0,0,0,1,1,1,1)))


[[[[ 0.  0.  0.  0.  0.]
   [ 0.  1.  2.  3.  0.]
   [ 0.  4.  5.  6.  0.]
   [ 0.  0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.  0.]
   [ 0.  7.  8.  9.  0.]
   [ 0. 10. 11. 12.  0.]
   [ 0.  0.  0.  0.  0.]]]


 [[[ 0.  0.  0.  0.  0.]
   [ 0. 11. 12. 13.  0.]
   [ 0. 14. 15. 16.  0.]
   [ 0.  0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.  0.]
   [ 0. 17. 18. 19.  0.]
   [ 0. 20. 21. 22.  0.]
   [ 0.  0.  0.  0.  0.]]]]
<NDArray 2x2x4x5 @cpu(0)>


## 11.transpose
交换矩阵的维度,输入的参数是一个tuple,该tuple的数字代表交换钱的维度，API会将这些维度按照tuple中的次序进行排列。

In [42]:
a = nd.zeros(shape = (2, 3, 4))
b = a.transpose((1, 2, 0))
print(b.shape)

(3, 4, 2)


## 12.swapaxes
交换矩阵的两个维度，输入参数```dim1```,```dim2```

In [43]:
a = nd.zeros(shape = (2, 3, 4))
b = a.swapaxes(dim1 = 0, dim2 = 1)
print(b.shape)

(3, 2, 4)


## 13.flip
按照指定的轴进行翻转

In [44]:
a = nd.array([[1, 2, 3], [4, 5, 6]])
print(a)
b = a.flip(axis = 0)
print(b)
c = a.flip(axis = 1)
print(c)


[[1. 2. 3.]
 [4. 5. 6.]]
<NDArray 2x3 @cpu(0)>

[[4. 5. 6.]
 [1. 2. 3.]]
<NDArray 2x3 @cpu(0)>

[[3. 2. 1.]
 [6. 5. 4.]]
<NDArray 2x3 @cpu(0)>


## 14.nanprod
求矩阵的乘积，当出现不是数字的情况，直接按照1处理。

同样类似的还有```nansum```，对不是数字的情况，按照0处理。

In [47]:
a = nd.ones(shape = (2, 3))
print(a)
b = a / 0
print(b)
print(nd.nanprod(a, axis = 0))
print(nd.nansum(a, axis = 0))


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

[[inf inf inf]
 [inf inf inf]]
<NDArray 2x3 @cpu(0)>

[1. 1. 1.]
<NDArray 3 @cpu(0)>

[2. 2. 2.]
<NDArray 3 @cpu(0)>


## 15.round
+ ```round```四舍五入
+ ```rint```就近取整并且靠近较小的一个(.5的时候)
+ ```floor```去尾
+ ```ceil```进1
+ ```trunc```靠近0取整
+ ```fix```靠近0取整

In [51]:
a = nd.array([-2.1, -1.9, 1.9, 2.1, 1.5, 2.5, -1.5, -2.5])
print("raw", a)
print("round", a.round())#[-2. -2.  2.  2.  2.  3. -2. -3.]  四舍五入
print("rint", a.rint()) #[-2. -2.  2.  2.  1.  2. -2. -3.]  选择较近，注意这个和numpy的结果不同
print("ceil", a.ceil()) #[-2. -1.  2.  3.  2.  3. -1. -2.]  进1
print("floor", a.floor())#[-3. -2.  1.  2.  1.  2. -2. -3.]  去尾
print("fix", a.fix())  #[-2. -1.  1.  2.  1.  2. -1. -2.]  选择靠近0
print("trunc", a.trunc())#[-2. -1.  1.  2.  1.  2. -1. -2.]  选择靠近0

a = nd.array([-2.1, -1.9, 1.9, 2.1, 1.5, 2.5, -1.5, -2.5])
b = np.array([-2.1, -1.9, 1.9, 2.1, 1.5, 2.5, -1.5, -2.5])
print("nd_rint", a.rint()) #[-2. -2.  2.  2.  1.  2. -2. -3.]  似乎是优先选择更小的
print("np_rint\n", np.rint(b)) #[-2. -2.  2.  2.  2.  2. -2. -2.]选择较近，并且靠近偶数

raw 
[-2.1 -1.9  1.9  2.1  1.5  2.5 -1.5 -2.5]
<NDArray 8 @cpu(0)>
round 
[-2. -2.  2.  2.  2.  3. -2. -3.]
<NDArray 8 @cpu(0)>
rint 
[-2. -2.  2.  2.  1.  2. -2. -3.]
<NDArray 8 @cpu(0)>
ceil 
[-2. -1.  2.  3.  2.  3. -1. -2.]
<NDArray 8 @cpu(0)>
floor 
[-3. -2.  1.  2.  1.  2. -2. -3.]
<NDArray 8 @cpu(0)>
fix 
[-2. -1.  1.  2.  1.  2. -1. -2.]
<NDArray 8 @cpu(0)>
trunc 
[-2. -1.  1.  2.  1.  2. -1. -2.]
<NDArray 8 @cpu(0)>
nd_rint 
[-2. -2.  2.  2.  1.  2. -2. -3.]
<NDArray 8 @cpu(0)>
np_rint
 [-2. -2.  2.  2.  2.  2. -2. -2.]


## 16.rsqrt
$1/\sqrt{x}$

还有类似的
+ ```cbrt```:$\sqrt[3]{x}$
+ ```qcbrt```:$1/\sqrt[3]{x}$
+ ```reciprocal```:$1/x$

In [52]:
a = nd.array([4, 4])
print(a.rsqrt())


[0.5 0.5]
<NDArray 2 @cpu(0)>


## 17.slice
假设输入矩阵的shape是$(d_0, d_1, ..., d_{n-1})$, 参数$begin = (b_0, b_1, ..., b_{m-1})$，$end=(e_0,e_1,..., e_{m-1}$，$step=(s_0, s_1, ...,s_{m-1})$，并且```m<=n```,输出的shape是$(|e_0-b_0|/|s_0|, ..., |e_{m-1}-b_{m-1}|/|s_{m-1}|, d_m, ..., d_{n-1})$

输出矩阵的第k维是从$b_k$（包含）开始以$s_k$为步长，达到$e_k$（不包含）的结果。

+ 如果$s_k$是None,则$s_k=1$
+ 如果$s_k>0$,其他为None,则$b_k=0, e_k=d_k$
+ 其他$b_k=d_{k-1}$, $e_k=-1$

In [61]:
x = nd.array([[  1.,   2.,   3.,   4.],
             [  5.,   6.,   7.,   8.],
             [  9.,  10.,  11.,  12.]])

y = nd.slice(x, begin=(None, 0), end=(None, 3), step=(-1, 2))
print(y)
z = nd.slice(x, begin=(2, 0), end=(-1, 3), step=(-1, 2))#与上面是相同的
print(z)


[[ 9. 11.]
 [ 5.  7.]
 [ 1.  3.]]
<NDArray 3x2 @cpu(0)>

[[ 9. 11.]
 [ 5.  7.]
 [ 1.  3.]]
<NDArray 3x2 @cpu(0)>


## 18.slice_axis
根据```axis```, ```beign```,```end```参数来分割矩阵，这个API可以代替[]操作，尤其是在```hybrid_forward```中，```hybridize```之后无法使用[]选取特定的子矩阵，可以通过该API代替。

In [62]:
x = nd.array([[  1.,   2.,   3.,   4.],
     [  5.,   6.,   7.,   8.],
     [  9.,  10.,  11.,  12.]])

y = nd.slice_axis(x, axis=1, begin=-3, end=-1) 
print(y)


[[ 2.  3.]
 [ 6.  7.]
 [10. 11.]]
<NDArray 3x2 @cpu(0)>


## 19.slice_like
根据另外一个矩阵y的shape，从输入矩阵x中取一部分元素。**从每个维度的0位置开始**，可以通过axes指定哪些维度需要按照y的shape进行slice

In [65]:
x = nd.ones(shape = (3, 4, 5))
y1 = nd.zeros(shape = (2, 3, 1))
print(x.slice_like(y1).shape)#2,3,1
print(x.slice_like(y1, axes = (0, 2)).shape)#2, 4, 1

(2, 3, 1)
(2, 4, 1)


## 20.take
根据提供的索引，沿着指定的轴slice输入矩阵
+ ```mode=clip```可以将index限制到shape范围内
+ ```mode=wrap```进行wrap around，即超出范围之后从0开始继续计数。

In [133]:
x = nd.array([1, 2, 3])
print(nd.take(x, nd.array([2])))
print(nd.take(x, nd.array([4]), mode = "clip"))#4被clip到2,默认clip，并且负数也会被clip

x = nd.array([[1,2], [3, 4], [5, 6]])
print(x)
y = nd.take(x, nd.array([[0, 1], [1, 2]]), axis = 1)#2会被clip到1，表示对x的每一行x[i]，依次取x[i][0], x[i][1]和x[i][1],x[i][1]（2-->1）
print(y)

print("**********clip***********")
y = nd.take(x, nd.array([[0, 2], [-1, -2]]), axis=1, mode='clip')#注意[0,2]中的2被clip到了1， [-1,-2]中的-1，-2都被clip到了0
print(y)
print("*******wrap around*******")
y = nd.take(x, nd.array([[0, 2], [-1, -2]]), axis=1, mode='wrap')#注意[0,2]中的2按照0,1,0,1被映射为了0，[-1,-2]中的-2被映射为0
print(y)


[3.]
<NDArray 1 @cpu(0)>

[3.]
<NDArray 1 @cpu(0)>

[[1. 2.]
 [3. 4.]
 [5. 6.]]
<NDArray 3x2 @cpu(0)>

[[[1. 2.]
  [2. 2.]]

 [[3. 4.]
  [4. 4.]]

 [[5. 6.]
  [6. 6.]]]
<NDArray 3x2x2 @cpu(0)>
**********clip***********

[[[1. 2.]
  [1. 1.]]

 [[3. 4.]
  [3. 3.]]

 [[5. 6.]
  [5. 5.]]]
<NDArray 3x2x2 @cpu(0)>
*******wrap around*******

[[[1. 1.]
  [2. 1.]]

 [[3. 3.]
  [4. 3.]]

 [[5. 5.]
  [6. 5.]]]
<NDArray 3x2x2 @cpu(0)>


## 21.pick
根据输入的索引和轴，从输入矩阵中选取元素。

给定一个输入矩阵shape(d0,d1)， 索引shape(i0,).输出矩阵为```input[i, indices[i]]```，shape为(i0,)的矩阵。

pick方法同样有```clip```和```wrap```模式

In [150]:
x = nd.array([[1, 2], [3, 4], [5, 6]])
print(x)

index = [1, 0, 0]#(0,1) (1, 0)
y = nd.pick(x, index = nd.array(index))#当axis = 1的时候与下面的例子相同。当axis = 0的时候，i和indices[i]互换（默认是1）
print(y)

y = x[list(range(3)), index]
print(y)


[[1. 2.]
 [3. 4.]
 [5. 6.]]
<NDArray 3x2 @cpu(0)>

[2. 3. 5.]
<NDArray 3 @cpu(0)>

[2. 3. 5.]
<NDArray 3 @cpu(0)>


## 22.one_hot
根据```depth```将一个输入矩阵转换为one_hot形式，该参数代表每个one_hot向量的长度。

In [66]:
a = nd.array([0,1 ,2, 3, 4])
b = nd.one_hot(a, depth = 5)
print(b)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<NDArray 5x5 @cpu(0)>


## 23.wait_to_read
该API会等待矩阵写入操作完成

具体可以参考https://www.jianshu.com/p/86975d2d69a5

In [69]:
import time
tic = time.time()
a = mx.nd.ones((1000,1000))
b = mx.nd.dot(a, a)
print(time.time() - tic)
b.wait_to_read()#保证所有之前的写入操作完成
print(time.time() - tic)

0.001993894577026367
0.08678555488586426


## 24.clip
将超出边界的数值clip到边界位置

In [73]:
a = nd.array([1, 2, 4, 5])
b = nd.clip(a, a_min = 2, a_max = 4)
print(b)


[2. 2. 4. 4.]
<NDArray 4 @cpu(0)>


## 25.repeat
矩阵的元素重复,默认情况下会把重复之后得到的矩阵flatten。

还可以通过axis指定重复的轴，这样结果不会flatten

In [75]:
x = nd.array([[1, 2],[3, 4]])
print(x)
print(nd.repeat(x, repeats = 2))
print(nd.repeat(x, axis = 1, repeats = 2))


[[1. 2.]
 [3. 4.]]
<NDArray 2x2 @cpu(0)>

[1. 1. 2. 2. 3. 3. 4. 4.]
<NDArray 8 @cpu(0)>

[[1. 1. 2. 2.]
 [3. 3. 4. 4.]]
<NDArray 2x4 @cpu(0)>


## 26.stack
把多个矩阵按照某个轴堆叠到一起。会增加维度，注意stack和concat的区别。


In [95]:
a = nd.ones(shape = (2, 3))
b = nd.zeros(shape = (2, 3))
x = nd.stack(a, b, axis = 0)
print(x)
y = nd.stack(a, b, axis = 1)
print(y)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
<NDArray 2x2x3 @cpu(0)>

[[[1. 1. 1.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [0. 0. 0.]]]
<NDArray 2x2x3 @cpu(0)>


## 27.concat
把多个矩阵连接到一起,需要指定concat的轴，并且不会增加维度。

In [85]:
a = nd.ones(shape = (2, 3))
b = nd.zeros(shape = (2, 3))
x = nd.concat(a, b, a, dim = 0)
print(x)
y = nd.concat(a, b, a, dim = 1)
print(y)


[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
<NDArray 6x3 @cpu(0)>

[[1. 1. 1. 0. 0. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 0. 1. 1. 1.]]
<NDArray 2x9 @cpu(0)>


## 28.where

输入是3个矩阵condition, x, y   
x和y是同样的shape，如果condition和x是同样的shape，那么如果condition元素为true,则返回x的对应元素，如果为false则返回y的对应元素。    
如果condition的shape和x不同，则一定是与x的第一维相同的1D矩阵，如果为true则返回x的对应行，否则返回y的对应行。

In [99]:
x = nd.array([[1, 2], [3, 4]])
y = nd.array([[5, 6], [7, 8]])
cond = nd.array([[0, 1], [-1, 0]])
print(x)
print(y)
print(nd.where(cond, x, y))


[[1. 2.]
 [3. 4.]]
<NDArray 2x2 @cpu(0)>

[[5. 6.]
 [7. 8.]]
<NDArray 2x2 @cpu(0)>

[[5. 2.]
 [3. 8.]]
<NDArray 2x2 @cpu(0)>


## 29.dot
+ 1D：内积   
+ 2D：矩阵乘法    
+ 3D：类似矩阵乘法，x是(n,m,k)的矩阵，y是(k,r,s)的矩阵，乘积是(n,m,r,s)的矩阵。```dot(x,y)[i,j,a,b] = sum(x[i,j,:]*y[:,a,b])```

注意ndarray的矩阵乘法和numpy的矩阵乘法的区别。

ndarray矩阵相乘时，使用第一个输入矩阵的最后一个维度，与第二个输入矩阵的第一个维度相乘。

numpy矩阵相乘时，使用第一个输入矩阵的最后一个维度，与第二个输入矩阵的倒数第二个维度相乘。

In [102]:
x = np.ones(shape = (1, 2, 3))
y = np.zeros(shape = (4, 3, 5))
z = np.dot(x, y)
print(z)
print(z.shape)#1,2,4,5

x = nd.ones(shape = (1, 2, 3))
y = nd.zeros(shape = (3, 4, 5))
z = nd.dot(x, y)
print(z)
print(z.shape)#1,2,4,5

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]
(1, 2, 4, 5)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]
<NDArray 1x2x4x5 @cpu(0)>
(1, 2, 4, 5)


## 30.norm
计算矩阵的范数

In [103]:
x = nd.array([[1, 2], [3, 4]])
print(x)
y = x.norm(axis = 1, ord = 1)
print(y)
y = x.norm(axis = 1, ord = 2)
print(y)
y = x.norm(ord = 2)
print(y)


[[1. 2.]
 [3. 4.]]
<NDArray 2x2 @cpu(0)>

[3. 7.]
<NDArray 2 @cpu(0)>

[2.236068 5.      ]
<NDArray 2 @cpu(0)>

[5.477226]
<NDArray 1 @cpu(0)>
